### ISSUE TITLE
Set a sensor to check if tv-show is among next_to_watch

### ISSUE THREAD

**Issue by vintage8902** [dylandoamaral/trakt-integration#100]
Is there a way I can check the attributes if say "House of Cards" is among the next episodes to watch?
I tried `{{ state_attr("sensor.trakt_next_to_watch_all", "title") }}` But that gave me nothing

`
- title: Neste sommer
  poster: https://image.tmdb.org/t/p/w500/mzxSOl4Hm5hFBXfKwAlAwL3yiw1.jpg
  fanart: https://image.tmdb.org/t/p/w500/lPKCKoBEUSk1XujYR7fJ5I3Umxt.jpg
  genres:
    - Comedy
  rating: 8.8
  studio: discovery+
  release: $day, $date $time
  airdate: '2016-02-28T20:30:00Z'
  episode: Episode 3
  number: S03E03
- title: House of Cards
  poster: https://image.tmdb.org/t/p/w500/hKWxWjFwnMvkWQawbhvC0Y7ygQ8.jpg
  fanart: https://image.tmdb.org/t/p/w500/yJjxO44EvaMYeeM9VHXHzdZ1kYL.jpg
  genres:
    - Drama
  rating: 8.026
  studio: Netflix
  release: $day, $date $time
  airdate: '2016-03-04T08:00:00Z'
  episode: Chapter 40
  number: S04E01
- title: Quantico
  poster: https://image.tmdb.org/t/p/w500/3ofY2mALEiE0QDyRlVOV3sDNMYC.jpg
  fanart: https://image.tmdb.org/t/p/w500/3rdQ4cbley3iOIkruTwMKDUzsLj.jpg
  genres:
    - Crime
    - Drama
    - Mystery
  rating: 6.5
  studio: ABC
  release: $day, $date $time
  airdate: '2016-03-07T01:00:00Z'
  episode: Alex
  number: S01E12`

**Comment by downey-lv** [comment]
Here's a binary sensor template to achieve this:

```
{% set data = state_attr("sensor.trakt_next_to_watch_all", "data") %}
{% set ns = namespace(title_found=False) %}

{% for item in data %}
  {% if item.title == "House of Cards" %}
    {% set ns.title_found = True %}
    {% break %}
  {% endif %}
{% endfor %}

{{ ns.title_found }}
```
