### ISSUE TITLE
Contributing to this integration by adding `Anticipated Shows` and `Anticipated Movies` sensors

### ISSUE THREAD

**Issue by mkanet** [dylandoamaral/trakt-integration#109]
I really like this integration.  I would like to contribute to this integration by adding some more useful sensors such as `Anticipated Shows` and `Anticipated Movies`.   **I think I'm almost there.**  It's retrieving the data from the respective API endpoints; and most, if not all the components are in place without generating any errrors.  However, the sensors are not getting created. 

Is there any chance you could take a quick look at what I might be missing [on my fork](https://github.com/mkanet/trakt-integration)?  Or, maybe you could give me a hint as to what I need to focus on?  I would be very grateful. 

Any tips would be greatly appreciated.

**Comment by dylandoamaral** [comment]
Hello put your fork as a PR and I will guide you !

**Comment by mkanet** [comment]
> Hello put your fork as a PR and I will guide you !

Wow. Thank you so much!  I will do that.  I will submit my PR soon.
