### ISSUE TITLE
Remove A Line

### ISSUE THREAD

**Issue by gdreelin** [dylandoamaral/trakt-integration#12]
Hey just noticed the line in the configuration yaml does not work (update_interval: 30). In your instructions the configuration is right on the Update Configuration Yaml but the next one down has that line in it. If you take it out the config will work fine. Just giving you heads up.  Not sure why it stopped working but it did it over the last day or so.

**Comment by dylandoamaral** [comment]
Yes itès the breaking change of the `v0.1.0`: https://github.com/dylandoamaral/trakt-integration/releases/tag/v0.1.0.
You have to remove this attribute.

**Comment by gdreelin** [comment]
Yeah I got that but I was saying on the instruction page you still have it.

![Untitled](https://user-images.githubusercontent.com/802649/131557729-6664d373-945f-4e37-ac94-f44a3c3490fe.png)

**Comment by dylandoamaral** [comment]
Whoops @gdreelin fixed thanks !
