### ISSUE TITLE
Trakt sensor seems to be late

### ISSUE THREAD

**Issue by kamilli0n** [dylandoamaral/trakt-integration#17]
I've been unable to get my Upcoming Shows card to update. It hasn't changed since the initial installation. I've tried reinstalling and rebooting but the same 3 shows persist after their air date/time.

Home Assistant Version: 2021.11.0
Trakt Integration: 0.1.1

**Comment by dylandoamaral** [comment]
Hi can you show me the trakt-integration yaml configuration and also the upcoming media card configuration.

**Comment by kamilli0n** [comment]
**configuration.yaml** (indented correctly in yaml file)

trakt_tv:
  language: en # Prefered language for movie/show title
  sensors:
    upcoming:
      show:
        days_to_fetch: 90 # How many days in the future you want to fetch
        max_medias: 3 # How many medias you want to fetch
      new_show:
        days_to_fetch: 90
        max_medias: 3
      movie:
        days_to_fetch: 90
        max_medias: 3

---------------------------------------
**upcoming media card** (nothing indented in card yaml)

type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_shows
title: Upcoming Shows
image_style: fanart
hide_empty: true
title_text: $title
line1_text: $episode
line2_text: $number
line3_text: $day, $date $time
line4_text: $empty
max: 10

**Comment by dylandoamaral** [comment]
Configurations seems to be fine, in developer tools, do you have the sensor `trakt_upcoming_shows` ?

**Comment by kamilli0n** [comment]
sensor is there and populated. This morning it did update but it seems to be about a day behind on its update. It's Friday, and it shows Thursdays shows it but did remove Wednesday's shows. Not a big deal, at least its updating.

**Comment by dylandoamaral** [comment]
If the sensor is there, then it's not the fault of this integration. Can you compare with trakt if the sensor is too late, if it is too late then open a new ticket.

**Comment by kamilli0n** [comment]
It appears to be late, as the "upcoming schedule" section on trakt does not match, one thing I noticed in the sensor is
airdate: '2021-11-05T00:00:00Z' (it shows 11-5 when actually its 11-4, perhaps a timezone issue?)  The date shows correctly in the upcoming media card as (Thursday 11-4 9:00PM). Timezone is set correctly in home assistant

**Comment by dylandoamaral** [comment]
Ok I will see what is going on

**Comment by dylandoamaral** [comment]
I saw nothing in the code, maybe the sensor was not updated yet. I close the issue for the moment.
