### ISSUE TITLE
Movies and New Shows sensors not pulling any data

### ISSUE THREAD

**Issue by codemagi** [dylandoamaral/trakt-integration#20]
Hi I just installed your awesome integration but the sensors `sensor.trakt_upcoming_movies` and `sensor.trakt_upcoming_new_shows` are not pulling any data.  

I can confirm however that `sensor.trakt_upcoming_premieres`, `sensor.trakt_upcoming_shows` and `sensor.trakt_upcoming_dvd` are all working.  

Wasn't sure if I hit a limit on API calls or something.

<img width="1059" alt="Screen Shot 2022-01-04 at 1 10 18 AM" src="https://user-images.githubusercontent.com/3393658/148022503-8b869e0d-b36e-4e62-b974-713cccf5262a.png">

**Comment by ryan13mt** [comment]
Do you have upcoming movies and new shows in your trakt watchlist? You have to include them in your watchlist first since these will only show your specific ones and not everything that will be coming out

**Comment by codemagi** [comment]
Ahh I misunderstood! Ok that works, thank you!
