### ISSUE TITLE
Integration not showing up in Integration page

### ISSUE THREAD

**Issue by davislp** [dylandoamaral/trakt-integration#22]
After installing trakt though HACS and following the setup process, once I get the section of adding trakt to HA Integrations, I search for trakt and it does not show up.

**Comment by dylandoamaral** [comment]
Did you restart Home assistant ?

**Comment by davislp** [comment]
I did restart HA several times; core, supervisor, and host just to be sure.

I did figure it out though. Apparently, sometimes, HACS integrations won't show up until you logout of HA and then log back in. I don't understand why, but that was the case here. After logging out and then back in, with no other changes, searching for trakt in the HA integrations made it come up. I appreciate the the response and will go ahead and close the issue.
