### ISSUE TITLE
Fix the readme syntax

### ISSUE THREAD

**Issue by dylandoamaral** [dylandoamaral/trakt-integration#3]
My english sucks and I was in a hurry sorry 😃.

**Comment by rishawsingh** [comment]
Hey, I wish to contribute. As I am new to the project and this seems like a good first issue, can you provide the scope for this issue with more details ?

**Comment by gdreelin** [comment]
I was able to get to work but a piece you missed is that the person has to install the integration of Trakt from the Integration section of HA so it adds the keys to HA. You went though the process for linking Trakt to HA but not where to put the keys. I had deleted all Trakt info when install yours to walk through it. I did it step by step but I was waiting on somewhere to add the link keys to it. So did a test and everything showed up, however if you both HACS version of Trakt install you will have some weird conflicts so I would note to remove it if you have it. In addition, it needs some instruction on creating a card for those that have not done one at all. I like this version and it is a great start.

**Comment by dylandoamaral** [comment]
@rishawsingh yes ofc sorry it was just a reminder to myself, I didn't think that you guys would help me that fast.

The goal is to provide enough information to the end user, for him to understand easily the goal of the integration, how to setup it and so on.

I also wanted to correct my grammar mistakes but it is already been done in a previous PR.

**Comment by dylandoamaral** [comment]
@gdreelin I cant access your link

**Comment by gdreelin** [comment]
> 
> 
> @gdreelin I cant access your link

Try this one: [https://docs.google.com/document/d/17JDNkDntdcE-AB4Hh-KBvIzQI_DYq9Hb/edit?usp=sharing&ouid=105685374782515477560&rtpof=true&sd=true](url)

**Comment by dylandoamaral** [comment]
Thank you !
Can you make your own PR with that change to close the issue ?
