### ISSUE TITLE
[Feat.] Improve Next To Watch sensor by adding 3 sensors

### ISSUE THREAD

**Issue by Anrolosia** [dylandoamaral/trakt-integration#51]
Hey @dylandoamaral ! I figured out it could be great to have 3 different sensors for the Next To Watch feature: all, only_aired, and only_upcoming. It will allow the user to build some nice dashboards (I build one with a column "to watch" with only_aired sensor, then another "Upcoming" with only_upcoming sensor.
If you think it can bring some value, let me know and I'll open a PR,
In the meantime, if you want to check and test/QA the code, here is the commit: https://github.com/Anrolosia/trakt-integration/commit/f35790fdce072f2bbb4c6be9a13c68b5e620fc1b
I also added some improvements to reduce calls to Trakt API

**Comment by dylandoamaral** [comment]
It can be a good idea don't know if it is a bit over engineered and if people will need that kind of feature 🤔

**Comment by Anrolosia** [comment]
Totally up to you. We can see if there is some traction on this request. Have a great day and keep me posted

**Comment by Anrolosia** [comment]
Small comment here to update the reference of the code I previously mentioned, it's now available on his own branch: https://github.com/Anrolosia/trakt-integration/tree/feature/multi-sensor-by-air-date
I did that to be able to help you with the support here ^^

**Comment by dylandoamaral** [comment]
Just to be sure what is the difference between the premieres already available and "only_upcoming" sensor ?

**Comment by Anrolosia** [comment]
What do you mean? The only_upcoming sensor is your active current watched shows with an air date greater than today. For example, if you follow a specific tv show, and the season ended this year, you'll be able to see it once it's plan to start again, for example in February 2023

**Comment by dylandoamaral** [comment]
True, the upcoming shows are quiet similar since they also show watched show but they also add show that are watchlisted. You can make the PR I will accept it !

**Comment by dylandoamaral** [comment]
Thank you for your work !

**Comment by GegoSK** [comment]
More options is always better. Could you please explain to me. What is difference between sensor.trakt_upcoming_shows and this change? I already have sensors: next to watch (only aired), upcoming episodes, upcoming series (premiere of next serie). :)

**Comment by dylandoamaral** [comment]
Ahah I was asking exactly the same question 4 days ago. According to me, the trakt upcoming shows will show you the next episode of the shows that you watched OR followed (added to a list) but this one will only work for the watched shows. I let @Anrolosia correct me if I am wrong.

**Comment by Anrolosia** [comment]
Hey @GegoSK ! Thanks for asking :)
So, in order to clarify, the new sensor I added is only based on your watched history, no need to create some lists or whatever.
I figured out an image with an example will clarify that:
![image](https://user-images.githubusercontent.com/1843399/197790784-e5550811-8635-497f-9652-b574d9931fd3.png)
So, on my side I don't manage any list, I'm using "SeriesGuide" on Android to track my tv show progress. As you can see on my screenshot, the new sensor show me 3 upcoming tv shows, but the "normal upcoming sensor" show 0 :(
I hope it answered your question, to you both :)

**Comment by GegoSK** [comment]
@Anrolosia: I read it few times and it is very confusing :). I am using lists on Trakt, but only "plan to watch". Anyway non of shows in that lists are in sensors attributes. I had two shows in _sensor.trakt_upcoming_shows_ for today. During writing of this post, it was updated, but still it is not correct. In calendar I see few more episodes. I will test your update soon. 

@dylandoamaral: Off topic 1: My _sensor.trakt_upcoming_new_shows_ is always empty. There should be fresh now shows which I plan to watch (from 1. episode of 1. season), right? How to add those shows in this sensor? 
Off topic 2: My sensor (_sensor.trakt_upcoming_movies_) shows two premieres, but the sensor state is 1. Bug?

**Comment by dylandoamaral** [comment]
Can you open a new issue for the off topic message please !

**Comment by GegoSK** [comment]
@dylandoamaral I checked all sensors and all of them has states value x-1. It could be problem in mine integration, because I deleted few lines from attributes: `{'title_default': '$title', 'line1_default': '$episode', 'line2_default': '$release', 'line3_default': '$rating - $runtime', 'line4_default': '$number - $studio', 'icon': 'mdi:arrow-down-bold'}`
I think that is the cause of the problem. What do you think?

Should I open issue based on the off topic 1?

**Comment by dylandoamaral** [comment]
You should always open an issue for each of your problem. So please creat them and I will answer your questions !
