### ISSUE TITLE
No sensors has been created

### ISSUE THREAD

**Issue by Ofir-P** [dylandoamaral/trakt-integration#59]
I have successfully added dylandoamaral trakt integration to my HA.
In his HACS documentation, it says 'the sensors may take a while to be created and populated.'
I left my HA PC on for about 4 hours and there are still no sensors showing up, I have also tried to restart the whole HA, and still nothing.

![image](https://user-images.githubusercontent.com/79255941/210656501-ef2d09b0-645b-4536-ac03-3a2660824f02.png)
This is the code right from my configuration.yaml:
![image](https://user-images.githubusercontent.com/79255941/210656747-574cb7d8-d459-4399-89f0-a5b57dbc7bca.png)

`trakt_tv:
  language: en # Prefered language for movie/show title
  timezone: Asia/Tel_Aviv # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3`

and yes I have data in my trakt account, using this website since 2017.
Thanks for helping!

**Comment by dylandoamaral** [comment]
Indeed, 4 hours are definitely more than enough normally. Do you have error logs coming from home assistant in your supervisor panel ?

**Comment by Ofir-P** [comment]
> 

Hi Dylan thanks for the quick reply!
Well, nothing unusual in my logs.

**Comment by dylandoamaral** [comment]
This is weird, did you try to delete the integration ?

**Comment by Ofir-P** [comment]
> This is weird, did you try to delete the integration ?

No, should I try?

**Comment by Ofir-P** [comment]
Okay I have re-added the integration and still showing no entities.
![image](https://user-images.githubusercontent.com/79255941/210774414-4b00c10c-c191-498f-bc24-69492af44d7b.png)

The redirect URL I used was
https://my.home-assistant.io/redirect/oauth
and I haven't clicked on the 'Authorize' button.

**Comment by dylandoamaral** [comment]
Did you follow this part: https://github.com/dylandoamaral/trakt-integration#workaround ?

**Comment by Ofir-P** [comment]
> Did you follow this part: https://github.com/dylandoamaral/trakt-integration#workaround ?

Yes.

**Comment by dylandoamaral** [comment]
Honestly, I don't know how I can help you without any piece of information. Explain me exactly what you did in home assistant and in trakt. And how do you know that no sensors are generated ?

**Comment by Ofir-P** [comment]
> 
I just followed the link you sent.

When I put the card it says this entity doesn't exist, also on the integration page it's showing no entities on your integration (all the other ones).

**Comment by Ofir-P** [comment]
After 24 hours the trakt thing in the integration page has been changed
![image](https://user-images.githubusercontent.com/79255941/210860477-82193437-b992-493b-b1a2-442d025d0c28.png)

**Comment by angrycvilleian** [comment]
Yep. I am getting this as well.

**Comment by dylandoamaral** [comment]
Ok thanks, at least I have something to start with !

**Comment by itzalgd24** [comment]
+1 for this error. Popped up when I updated to 23.1.1 this morning.

**Comment by echopage** [comment]
Me too

**Comment by Ofir-P** [comment]
> Ok thanks, at least I have something to start with !

Error is now gone, I reinstalled the integration and still no entities showing up.
Note - I have created another API in trakt website
with Redirect URL 
`https://my.home-assistant.io/redirect/oauth`

**Comment by dylandoamaral** [comment]
It still does not work with `https://my.home-assistant.io/redirect/oauth` redirection ? I tried in the current home assistant version and it worked well.

**Comment by dylandoamaral** [comment]
You did great. 

Sorry if I am annoying with my questions and if I ask simple things that you already did. The fact is that I don't know why this is happening to you. Since I can't reproduce it myself, I can't help you that much.

Here are things that may help you (If you haven't tried yet):
- Check your version of home assistant and upgrade it to the latest
- Check in developer tools (in state) if there are no sensors starting with `sensor.trakt`
- Remove the timezone temporarly to see if it causes issues

If nothing is working, then I hope someone else will allow us to make progress.

During this time you can look at https://github.com/custom-components/sensor.trakt maybe it will work for you.

**Comment by Ofir-P** [comment]
> You did great.
> 
> Sorry if I am annoying with my questions and if I ask simple things that you already did. The fact is that I don't know why this is happening to you. Since I can't reproduce it myself, I can't help you that much.
> 
> Here are things that may help you (If you haven't tried yet):
> 
> * Check your version of home assistant and upgrade it to the latest
> * Check in developer tools (in state) if there are no sensors starting with `sensor.trakt`
> * Remove the timezone temporarly to see if it causes issues
> 
> If nothing is working, then I hope someone else will allow us to make progress.
> 
> During this time you can look at https://github.com/custom-components/sensor.trakt maybe it will work for you.

You are not annoying at all, and I appreciate your help!

This is the version I'm using currently 
![image](https://user-images.githubusercontent.com/79255941/211407069-70935b3f-739b-4a32-a1f6-79fec892caea.png)

Developer tools - 
![image](https://user-images.githubusercontent.com/79255941/211407175-aa906987-c7ee-4b93-a346-210cd0e7a14d.png)
![image](https://user-images.githubusercontent.com/79255941/211407206-b4081f96-8864-48bd-b4de-55924f506789.png)
Time zone - I couldn't remove it completely so I have tried Europe/Paris
When removed the line I got this error on the configuration.yaml file
Invalid config for [trakt_tv]: value must be one of ['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera',
![image](https://user-images.githubusercontent.com/79255941/211408591-3bd2fb78-f213-4aaa-94eb-3b10ba2cbee5.png)
Configuration.yaml:
`trakt_tv:
  language: en # Prefered language for movie/show title
  timezone: Europe/Paris
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3`

**Comment by dylandoamaral** [comment]
Honestly you did everything perfectly, I don't know how I can help you now...

@itzalgd24 or @echopage do you still have an error ?

**Comment by rzechu** [comment]
Same problem here
OAuth problem solved by changing redirect uri to https://my.home-assistant.io/....

> Success!
> Successfully authenticated with Trakt.
> Created configuration for Trakt.

Got only 1 default entity
![image](https://user-images.githubusercontent.com/45091660/211540589-0156936c-394b-4220-84dd-5d03c1c4e8e4.png)

![image](https://user-images.githubusercontent.com/45091660/211540551-25021155-8ed0-4638-9086-2e0c91995ec7.png)


Got working only 1 entity and 1 card
```
resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
    type: js
type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_calendar
title: Upcoming Episodes
image_style: fanart
hide_empty: true
title_text: $title
line1_text: $episode
line2_text: $number
line3_text: $day, $date $time
line4_text: $empty
max: 10
```
![image](https://user-images.githubusercontent.com/45091660/211540819-cac33d8e-36d1-49e6-bfbb-e5b83e20edef.png)

My configuration.yaml
```
trakt_tv:
  language: en
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3
```

Cant add upcoming for movies

> There are five sensors available under the sensors > upcoming array:
> show for TV Shows (actually, episodes). Creates sensor.trakt_upcoming_shows
> new_show for New Shows (series premiers). Creates sensor.trakt_upcoming_new_shows

**Comment by Ofir-P** [comment]
> 

How did you manage to save the configuration.YAML without a timezone?
I copied your code to my configuration.YAML and i get the error:
`Configuration invalid!

Invalid config for [trakt_tv]: value must be one of ['Africa/Abidjan',`

**Comment by Ofir-P** [comment]
> Same problem here OAuth problem solved by changing redirect uri to https://my.home-assistant.io/....
> 
> > Success!
> > Successfully authenticated with Trakt.
> > Created configuration for Trakt.
About this:

Same problem here
OAuth problem solved by changing redirect uri to https://my.home-assistant.io/....

Success!
Successfully authenticated with Trakt.
Created configuration for Trakt.

can you send me the full link you've entered in the trakt page of 'Redirect URI' ? also after it redirects you after adding the integration what is the link that shown below? Is your local or a cloud link? mind sending me that too? (you can censor the link a bit so I can understand what to put in there)

**Comment by dylandoamaral** [comment]
For the redirect URI, here is what worked for me in my dev environment: `https://my.home-assistant.io/redirect/oauth`

**Comment by rzechu** [comment]
I sucessfully connected trakt no problem just saying workaroud solved problem
https://my.home-assistant.io/redirect/oauth/?code=d9f48XXXXXX&state=eyJhbGciOiXXXX.n_XXXXXX

And have no problem with saving configuration.yaml without timezone
But configured as you wanted and after restart nothing changed
```
trakt_tv:
  language: en
  timezone: Europe/Paris # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 3
```

**Comment by dylandoamaral** [comment]
Everything is working now ?

**Comment by dylandoamaral** [comment]
I never used something related to nabu.casa but it should be the same thing from (the redirect URI red square):

![image](https://user-images.githubusercontent.com/37652599/211558251-fe0ae625-e784-4e05-a45b-3b310a19a2b7.png)

**Comment by Ofir-P** [comment]
> I never used something related to nabu.casa but it should be the same thing from (the redirect URI red square):
> 
> ![image](https://user-images.githubusercontent.com/37652599/211558251-fe0ae625-e784-4e05-a45b-3b310a19a2b7.png)

There is a diff between the Redirect URL in trakt (which I set to https://my.home-assistant.io/redirect/oauth)
then the 'Your instance URL' that shows in the next screen after putting in the ID and secret code
I wanna know what instance rzechu used and then clicked on Link Account because I think that might be my solution to this case.

**Comment by rzechu** [comment]
Any ideas about missing (not added) sensors or upcoming-media-card configuration?
No info about movies only upcoming show

> Got only 1 default entity (reinstalled trakt integration) ![image](https://user-images.githubusercontent.com/45091660/211540589-0156936c-394b-4220-84dd-5d03c1c4e8e4.png)
> 
> ![image](https://user-images.githubusercontent.com/45091660/211540551-25021155-8ed0-4638-9086-2e0c91995ec7.png)
> 
> Got working only 1 entity and 1 card
> 
> ```
> resources:
>   - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
>     type: js
> type: custom:upcoming-media-card
> entity: sensor.trakt_upcoming_calendar
> title: Upcoming Episodes
> image_style: fanart
> hide_empty: true
> title_text: $title
> line1_text: $episode
> line2_text: $number
> line3_text: $day, $date $time
> line4_text: $empty
> max: 10
> ```
> 
> ![image](https://user-images.githubusercontent.com/45091660/211540819-cac33d8e-36d1-49e6-bfbb-e5b83e20edef.png)
> 
> My configuration.yaml
> 
> ```
> trakt_tv:
>   language: en
>   timezone: Europe/Paris # Prefered timezone #added this but no difference
>   sensors:
>     upcoming:
>       show:
>         days_to_fetch: 30
>         max_medias: 10
>       movie:
>         days_to_fetch: 45
>         max_medias: 5
>     recommendation:
>       show:
>         max_medias: 3
>       movie:
>         max_medias: 3
> ```
> 
> Cant add upcoming for movies and I dont see any other sensors even after restart ( show / movie / recommendation etc)
> 
> > There are five sensors available under the sensors > upcoming array:
> > show for TV Shows (actually, episodes). Creates sensor.trakt_upcoming_shows
> > new_show for New Shows (series premiers). Creates sensor.trakt_upcoming_new_shows

**Comment by dylandoamaral** [comment]
There are two issues at the same time here, it is difficult to handle them both at the same time...

**Comment by dylandoamaral** [comment]
I tried a new release I am not very confident but maybe it will help.

**Comment by Ofir-P** [comment]
> I tried a new release I am not very confident but maybe it will help.

Where can I see that?

**Comment by dylandoamaral** [comment]
On home assistant, in HACS you should see the update.

**Comment by Ofir-P** [comment]
> On home assistant, in HACS you should see the update.

Uninstalled, updated via HACS, and reinstalled.
![image](https://user-images.githubusercontent.com/79255941/212070933-d1e12b1f-869e-4472-9716-3687d7a30f36.png)
same issue.

**Comment by echopage** [comment]
Sorry for the delay... Same problem as Ofir-P, I redid the same procedure as Ofir-P with the difference that I'm not under Nabu-Casa, now it no longer gives me an oauth error but the result is the same, no sensor!
