### ISSUE TITLE
502 status Bad Gateway

### ISSUE THREAD

**Issue by giloser** [dylandoamaral/trakt-integration#64]
Hi,

first thanks for you hard work, I had the issue #63 and you fix it in no time !
but since I got the following error and in the log it say if we see the error to raise an issue so here I am.

I tried searching in the closed issues and on the net but didn't found a solution yet.
here is the log hope it can help you fix it or explaining what I did wrong.

thanks

`Unexpected error fetching trakt data: Can't request users/hidden/calendar?type=show with get because it returns a 502 status code with reason Bad Gateway. If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Unexpected error fetching trakt data: Can't request shows/195503/progress/watched with get because it returns a 502 status code with reason Bad Gateway. If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Unexpected error fetching trakt data: Can't request shows/119137/progress/watched with get because it returns a 502 status code with reason Bad Gateway. If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 289, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 236, in fetch_next_to_watch
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 191, in fetch_upcoming
    raw_medias = await self.fetch_watched(excluded_shows)
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 94, in fetch_watched
    hidden_items = await self.request(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 75, in request
    raise TraktException(f"{error}\n{guidance}")
custom_components.trakt_tv.exception.TraktException: Can't request users/hidden/calendar?type=show with get because it returns a 502 status code with reason Bad Gateway.
If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.`

**Comment by dylandoamaral** [comment]
According to the API, it means that the trakt server had a problem. Do you still have the issue ?

**Comment by giloser** [comment]
yes I still have the issue. 
I waited to see if it was temporary, I tried to reinstall once again from scratch but still the same.

**Comment by hindsight2021** [comment]
I have the same exact error string.

**Comment by dylandoamaral** [comment]
I tried something in 0.7.4. I don't think it will fix the bug... Nevermind I also update the error to have better information, don't hesitate to tell me what is the new error message.

**Comment by giloser** [comment]
thanks for the fast update ! 

here is the new trace :

`Logger: custom_components.trakt_tv
Source: custom_components/trakt_tv/apis/trakt.py:77
Integration: Trakt ([documentation](https://github.com/dylandoamaral/trakt-integration), [issues](https://github.com/dylandoamaral/trakt-integration/issues))
First occurred: 07:44:59 (1 occurrences)
Last logged: 07:44:59

Unexpected error fetching trakt data: Can't request calendars/my/shows/premieres/2023-01-29/33 with get because it returns a 502 status code with content <!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>api.trakt.tv | 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" /> </head> <body> <div id="cf-wrapper"> <div id="cf-error-details" class="p-0"> <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8"> <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2"> <span class="inline-block">Bad gateway</span> <span class="code-label">Error code 502</span> </h1> <div> Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information. </div> <div class="mt-3">2023-01-30 06:44:59 UTC</div> </header> <div class="my-8 bg-gradient-gray"> <div class="w-240 lg:w-full mx-auto"> <div class="clearfix md:px-8"> <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center"> <div class="relative mb-10 md:m-0"> <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span> <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span> </div> <span class="md:block w-full truncate">You</span> <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3"> Browser </h3> <span class="leading-1.3 text-2xl text-green-success">Working</span> </div> <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center"> <div class="relative mb-10 md:m-0"> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer"> <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span> <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span> </a> </div> <span class="md:block w-full truncate">Brussels</span> <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3"> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer"> Cloudflare </a> </h3> <span class="leading-1.3 text-2xl text-green-success">Working</span> </div> <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center"> <div class="relative mb-10 md:m-0"> <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span> <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span> </div> <span class="md:block w-full truncate">api.trakt.tv</span> <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3"> Host </h3> <span class="leading-1.3 text-2xl text-red-error">Error</span> </div> </div> </div> </div> <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8"> <div class="clearfix"> <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed"> <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2> <p>The web server reported a bad gateway error.</p> </div> <div class="w-1/2 md:w-full float-left leading-relaxed"> <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2> <p class="mb-6">Please try again in a few minutes.</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300"> <p class="text-13"> <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">79183dfcabfe2e5c</strong></span> <span class="cf-footer-separator sm:hidden">&bull;</span> <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1"> Your IP: <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button> <span class="hidden" id="cf-footer-ip">213.211.148.17</span> <span class="cf-footer-separator sm:hidden">&bull;</span> </span> <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" id="brand_link" target="_blank">Cloudflare</a></span> </p> <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script> </div> </div> </div> </body> </html> . If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 291, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 248, in fetch_upcomings
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 199, in fetch_upcoming
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 83, in fetch_calendar
    return await self.request(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 72, in request
    return await self.request(method, url, **kwargs)
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 77, in request
    raise TraktException(f"{error}\n{guidance}")
custom_components.trakt_tv.exception.TraktException: Can't request calendars/my/shows/premieres/2023-01-29/33 with get because it returns a 502 status code with content <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>


<title>api.trakt.tv | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="inline-block">Bad gateway</span>
              <span class="code-label">Error code 502</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2023-01-30 06:44:59 UTC</div>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Brussels</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">api.trakt.tv</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
              
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">79183dfcabfe2e5c</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">213.211.148.17</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
</div>
</body>
</html>

.
If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.`

**Comment by NederWeb** [comment]
Having the same issue, comparable to the others.

From the log:
https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv

**Comment by dylandoamaral** [comment]
0.7.5 should fix the error as described in https://trakt.docs.apiary.io/#introduction/status-codes. If the issue persist, I don't know how to fix it. It seems to be a trakt issue not an intgegration one.

**Comment by giloser** [comment]
Hi thanks,

I update last night and today I tried to restart from scratch.

and sorry I still got an error.
if you say the issue is on the trakt side, could we create a call on their side then? could you explain what we should ask?
What I don't understand is that it works from some so what is different from me that from the others?

Thanks a lot
here is the log:

Logger: custom_components.trakt_tv
Source: custom_components/trakt_tv/apis/trakt.py:80
Integration: Trakt (documentation, issues)
First occurred: 14:50:27 (2 occurrences)
Last logged: 14:51:48

Unexpected error fetching trakt data: Can't request recommendations/shows?limit=3&ignore_collected=false with get because it returns a 401 status code with content . If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Unexpected error fetching trakt data: Can't request users/hidden/calendar?type=show with get because it returns a 401 status code with content . If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 294, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 268, in fetch_recommendations
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 261, in fetch_recommendation
    return await self.request(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 80, in request
    raise TraktException(f"{error}\n{guidance}")
custom_components.trakt_tv.exception.TraktException: Can't request recommendations/shows?limit=3&ignore_collected=false with get because it returns a 401 status code with content .
If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.

**Comment by dylandoamaral** [comment]
You should create another issue, it is not a 502 error but a 401 (unauthorized) one.

**Comment by giloser** [comment]
ok thanks I'll do that

**Comment by dylandoamaral** [comment]
Seems to be ok now
