### ISSUE TITLE
401 status code

### ISSUE THREAD

**Issue by giloser** [dylandoamaral/trakt-integration#66]
Hi, 

as requested I create a new issue with the current log of the error I got.

I tried again to start from the beginning and remove everything but I still got the exact same error.
What should I try o r check to fix this?

thanks a lot

Logger: custom_components.trakt_tv
Source: custom_components/trakt_tv/apis/trakt.py:80
Integration: Trakt ([documentation](https://github.com/dylandoamaral/trakt-integration), [issues](https://github.com/dylandoamaral/trakt-integration/issues))
First occurred: 15:04:58 (1 occurrences)
Last logged: 15:04:58

Unexpected error fetching trakt data: Can't request recommendations/shows?limit=3&ignore_collected=false with get because it returns a 401 status code with content . If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 294, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 268, in fetch_recommendations
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 261, in fetch_recommendation
    return await self.request(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 72, in request
    return await self.request(method, url, **kwargs)
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 80, in request
    raise TraktException(f"{error}\n{guidance}")
custom_components.trakt_tv.exception.TraktException: Can't request recommendations/shows?limit=3&ignore_collected=false with get because it returns a 401 status code with content .
If you find this error, please raise an issue at https://github.com/dylandoamaral/trakt-integration/issues.

**Comment by dylandoamaral** [comment]
Did you already succeed to install this integration before ?

**Comment by giloser** [comment]
no it's my first try

**Comment by giloser** [comment]
yes the integration says it worked and everything

**Comment by dylandoamaral** [comment]
Do you still have the issue

**Comment by giloser** [comment]
hi thanks for the followup!

no right now I have a 500 so saying the trakt server has an issue...

I propose we close I'll try your dev environment and come back to you to tell what I found.
