### ISSUE TITLE
Pull in watch history

### ISSUE THREAD

**Issue by YorkshiremanJim** [dylandoamaral/trakt-integration#81]
It would be amazing to have something that pulled in watch history.  Either at a detailed level, or even just how many episodes, movies, or length of time watched etc... 
To track your usage on graph would be awesome..

**Comment by Efunch** [comment]
It would be great indeed.

**Comment by downey-lv** [comment]
Created a PR to have all of the statistics on your watch history, detailed history should be fixed under #87
