### ISSUE TITLE
How do I remove certain TV show recommendations ?

### ISSUE THREAD

**Issue by brewston** [dylandoamaral/trakt-integration#82]
I don't see to be able to tell the trakt UI to ignore some shows it recommends. When I try to add them to an exclude list for recommendations, HA gives an error when checking the yaml. Thanks.

**Comment by dylandoamaral** [comment]
Can you show me your configuration please.

**Comment by brewston** [comment]
Sure 

`trakt_tv:
  language: en
  timezone: GMT
  sensors:
    upcoming:
      show:
        days_to_fetch: 30
        max_medias: 10
      movie:
        days_to_fetch: 45
        max_medias: 5
    recommendation:
      show:
        max_medias: 3

      movie:
        max_medias: 3
    next_to_watch:
      all:
        max_medias: 3
        exclude:
          - the-young-ones
          - community
          - below-deck
          - below-deck-mediterranean
          - below-deck-sailing-yacht
          - benidorm
          - the-boys
          - rick-and-morty
          - chernobyl
          - You-Are-What-You-Eat`
          -

Those are just shows to ignore, not recommended ones.
