### ISSUE TITLE
Sensors empty

### ISSUE THREAD

**Issue by skank01** [dylandoamaral/trakt-integration#88]
Hi

I have 3 upcoming sensors.
All 3 are empty.
How can that be?

I just want to see upcoming new movies, new episodes and completely new series.

Thx

**Comment by dylandoamaral** [comment]
Maybe you don't have upcoming movies/series configured in trakt ?

**Comment by skank01** [comment]
Yes i do
Watchlist:
![image](https://github.com/dylandoamaral/trakt-integration/assets/53368406/3990641d-8022-4708-ac55-293a44ba95c1)

Even in the anticipated

![image](https://github.com/dylandoamaral/trakt-integration/assets/53368406/bcd41325-5fb9-406b-8bf1-8ce6db78fdd3)

**Comment by skank01** [comment]
I'm seeing 2 errors in log:

First:
Unexpected error fetching trakt data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 368, in retrieve_data
    data = await gather(
           ^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 320, in fetch_upcomings
    data = await gather(
           ^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 277, in fetch_upcoming
    raw_medias = [media for medias in data for media in medias]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 277, in <listcomp>
    raw_medias = [media for medias in data for media in medias]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable




Second:
Can't request calendars/my/movies/2024-05-12/15 with get because it returns a 502 status code with content <!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>api.trakt.tv | 502: Bad gateway</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" /> </head> <body> <div id="cf-wrapper"> <div id="cf-error-details" class="p-0"> <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8"> <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2"> <span class="inline-block">Bad gateway</span> <span class="code-label">Error code 502</span> </h1> <div> Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=api.trakt.tv" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information. </div> <div class="mt-3">2023-11-30 15:06:59 UTC</div> </header> <div class="my-8 bg-gradient-gray"> <div class="w-240 lg:w-full mx-auto"> <div class="clearfix md:px-8"> <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center"> <div class="relative mb-10 md:m-0"> <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span> <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span> </div> <span class="md:block w-full truncate">You</span> <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3"> Browser </h3> <span class="leading-1.3 text-2xl text-green-success">Working</span> </div> <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center"> <div class="relative mb-10 md:m-0"> <a href="https://www.cloudflare.com/5xx-error-landing?

**Comment by dylandoamaral** [comment]
HI, I don't, generally 5XX errors are due to trakt servers.

**Comment by skank01** [comment]
Hi,
Strange but now i have 1 movie in the upcoming sensors..
Which is great, so it works, but a bit pity it shows not many movies..
![up](https://github.com/dylandoamaral/trakt-integration/assets/53368406/08687574-9d2d-4189-99a9-303c72687778)

Even my shows are empty

Any idea how it comes?
Should i do something in trakt.tv ?

Arent the anticapted shown?
I got upcoming movies and shows, and also all_upcoming movies and shows, and almost everything is empty

**Comment by dylandoamaral** [comment]
Indeed, you have to do something in trakt. For upcoming movies and shows, you have to go to https://trakt.tv/movies/anticipated and add some of them to the watchlist. If they are upcoming in less than 90 days (as your configuration say), it will appear. For show, it depends if you selected show or new_show: I advise you to look at https://trakt.docs.apiary.io/#reference/calendars/get-shows for more information.
